### ISSUE TITLE
CloudFormation templates

### ISSUE THREAD

**Issue by PaulDuvall** [stelligent/cloudformation_templates#1]
@LevonBecker You know we've got this? https://github.com/stelligent/stelligent_commons/tree/master/cloudformation

**Comment by LevonBecker** [comment]
Oh cool thanks!

## 

Levon Becker | Advanced DevOps Automation Engineer | 503.341.2312 | www.stelligent.com http://www.stelligent.com/ | Continuous Integration and Delivery. Cloud Migration. Elastic Operations

**Comment by LevonBecker** [comment]
The idea of this repo is to have an organized collection of general reusable templates and some specific labs. All with the correct .template extension name, with descriptive standardized naming and at least a decent summary of the purpose of each in the Readme. I like to dedicate repositories to specific subject or project. That way the instructions (root readme) can focus on the code collection (repo) and not be overwhelming to fresh eyes. It's part why everyone usually creates a repo for a single Chef cookbook. Well that and so you can add the root to a Berksfile, run through automated testing just on that cookbook etc. It could just be my OCD side showing, but this is how I've always done it with customers and my personal Github organizations. If you would rather me move the code the the commons I will, just let me know.

**Comment by PaulDuvall** [comment]
@LevonBecker 

> All with the correct .template extension name

AWS is using .json these days and the standardized NIST references the same: http://docs.aws.amazon.com/quickstart/latest/accelerator-nist/templates.html

> I like to dedicate repositories to specific subject or project.

Ok. We should collaborate to get the stuff from https://github.com/stelligent/stelligent_commons/tree/master/cloudformation into this repo in the manner you're suggesting. But, we'll want to avoid the entropy that could occur if we don't synchronize on this.
